sonar.projectKey=jhmelomo_ucv-ate-si-lab11
sonar.organization=jhmelomo
sonar.projectName=UCV Alpha Beta Lab
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8